---
version: 2

defaults: &defaults
  docker:
    - image: gcr.io/cedar-hawk-222400/deployer:develop
  environment:
    APP_HOSTNAME: example.raywalker.it
    CONTAINER_PREFIX: example
    SOURCE_BUCKET: www.raywalker.it
    WP_DB_PREFIX: fnord_

job_definitions:
  build_steps: &build_steps
    working_directory: ~/
    steps:
      - setup_remote_docker
      - run: activate-gcloud-account.sh
      - run: mkdir -p /tmp/workspace/var
      - run: mkdir -p /tmp/workspace/src
      - run: echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num
      - run: make

jobs:
  go:
    <<: *defaults
    <<: *build_steps

workflows:
  version: 2
  branch:
    jobs:
      - go:
          context: raywalker-it-common
          filters:
            branches:
              only: /.*/
